### ISSUE TITLE
Camera not showing on mobile devices

### ISSUE THREAD

**Issue by Ikpeba4ll** [basst314/ngx-webcam#14]
I can't get the camera working on mobile device.. How can i resolve that? Thank you!!

**Comment by basst314** [comment]
Hi @Ikpeba4ll,

Is the demo-page working on that phone?
https://basst314.github.io/ngx-webcam/?

Phones have to be „relatively current“ regarding their OS in order to support the required WebRTC functionality.

Cheers!

**Comment by Ikpeba4ll** [comment]
The demo is working on phone but not in my app

**Comment by basst314** [comment]
Hi @Ikpeba4ll,

what happens when you load your app on the phone? Any errors?
Also, what version of ngx-webcam / Angular do you use, and how did you integrate the library into your app?

For integration and usage you may check the source code in this library, or in the explicit [demo-project](https://github.com/basst314/ngx-webcam-demo) I set up.

Let me know if that helps.

**Comment by Ikpeba4ll** [comment]
There is no error.. ngx-webcam version is 0.1.5 and angular is 5.2

**Comment by basst314** [comment]
Actually, there‘s nothing extra that needs to be done for it to run on a capable mobile device.

If the demo page works for you, your phone is current enough to support WebRTC. The library in your app should work as well.

Please check that the app and webcam is working when you access it with your desktop pc, and nothing else in the app is failing on the mobile device. Try to create a minimal running demo (like the one I provided).

Does the mobile device ask you to access the webcam? Do you see an icon in the addressbar for webcam-access? Did you give permissions to access the webcam?

I guess you have to provide a little more information here in order to get the answer.

But it seems like the problem might lie in your app itself or in the way ngx-webcam is integrated there, since the demo-page is working for you.

**Comment by Ikpeba4ll** [comment]
My phone does not request permission to access the camera...

**Comment by Ikpeba4ll** [comment]
Hello team,
I have noticed that the camera doesn't work on other devices and not only mobile phones.. How can I resolve this

**Comment by Ikpeba4ll** [comment]
Moreover do I need a https to access it on other devices?

**Comment by basst314** [comment]
Were you able to resolve the issue?

**Comment by Ikpeba4ll** [comment]
yes

**Comment by poojas17** [comment]
How did you resolve this issue?
webcam is triggering snaps on all browsers and their incognitos except Chrome incognito mode.

**Comment by mspace** [comment]
@Ikpeba4ll  I can confirm this behaviour too.
If accessed via https, it asks for permission. If accessed via http I get 'Cannot read UserMedia from MediaDevices'
