### ISSUE TITLE
Not working with cordova

### ISSUE THREAD

**Issue by mick88** [basst314/ngx-webcam#17]
The component does not appera to work when wrapped in a cordova app. There's no error message in console. I need a component that works on web as well as in apk.

**Comment by basst314** [comment]
Hi @mick88,

Does your project live on github? I’d like to take a look at the integration. Could you point me to your source code? 

Haven’t really worked with cordova before, but I will see what I can do.

Thanks

**Comment by basst314** [comment]
In the meantime - could you verify that no error was emitted via the `initError` event emitter?

Thanks!

**Comment by basst314** [comment]
Hi @mick88,
were you able to check the `initError` event emitter for messages?
Thanks

**Comment by basst314** [comment]
Okay, yeah at least common browsers require an https connection in order to access sensitive devices such as the camera. Might be the same in cordova if content is only served over http.

Is it possible to serve this content over https as well? Could you try if that solves your problem?

I might also be going to test this library with a cordova app if I have time to build one.  ;)
Leaving this ticket open for now.

**Comment by basst314** [comment]
Hi @monikagupta78,

can you share your project and/or project-code?

Things to check:
* Do you serve your content over https?
* Did you check whether there are any errors in the `initError` event emitter after initialization?
* Did you allow camera access?
* Does your browser support the necessary APIs? (Validate by visiting the [demo page](https://basst314.github.io/ngx-webcam/)

Thanks

**Comment by basst314** [comment]
No reply from requester, closing this issue.
