### ISSUE TITLE
Circular Frame

### ISSUE THREAD

**Issue by Prathik-Jain** [basst314/ngx-webcam#18]
I would like to change the shape of `<webcam></webcam>`  to be circular - even if the photos are rectangular I want the Frame to be circular - 
Tried editing `.webcam` `video` `.webcam-wrapper` I can get the result in chrome dev tools but not through code.

**Comment by Prathik-Jain** [comment]
@basst314

**Comment by basst314** [comment]
Hi @Prathik-Jain,

this should be achievable with CSS I believe. 
I will try and let you know as soon as possible.

Cheers

**Comment by Prathik-Jain** [comment]
Woah! :tada: !!
It works when I change the style in my global style sheet.

Can you please explain why does it not working in a component style sheet?
Thanks @basst314

**Comment by basst314** [comment]
Hi @Prathik-Jain,

I'm glad to hear that it worked! 

Things like this must go into the global style sheet, since Angular runs style encapsulation per component, which means that a style defined in a component css will only be applied to its own template (and never to others). For more information, see [here](https://angular.io/guide/component-styles#style-scope).

Cheers!
