### ISSUE TITLE
Reflect webcam

### ISSUE THREAD

**Issue by cuongnl-pnc** [basst314/ngx-webcam#23]
Hi.
When I use my mobile phone with front camera, it seems not my expected image, it need to be **reflected**.
How can I do this?

**Comment by basst314** [comment]
Hi @cuongnl-pnc,
Thanks for raising this. You‘re right, since most phones mirror the image horizontally, it does not correspondent to the image that is returned by the webcam. The webcam returns just the image that it sees.
I‘m not sure if that can be resolved but I will look into it in a couple of days when I have some more time.

The photos you take should be mirror-able though with any kind of library.

**Comment by basst314** [comment]
Hi @cuongnl-pnc,

I looked into this a little more. There are differences among browsers what information is returned about the active camera (i.e. is it user-facing or not). 

During my tests I noticed, that my desktop and laptop cameras, even if they are built-in, don't reveil whether they are user-facing or not, but my smartphone did reveal it.
So I should be able to build a mechanism into the existing code to mirror the camera image if the camera diagnoses itself as user-facing.

I will also provide mechanisms to turn-off this feature as it might not be desirable under certain circumstances.

Cheers!

**Comment by basst314** [comment]
Hi @cuongnl-pnc,

I released a new version of this library ([0.2.0](https://github.com/basst314/ngx-webcam/releases)) that mirrors the webcam image horizontally when the active webcam is detected to be user-facing.
Please note that not all devices might reveal their facingMode.

I also provided a new parameter with which the mirroring can be controlled explicitly. See the documentation for details.

Cheers!
