### ISSUE TITLE
Not able to open camera on IPad and Microsfot Windows surface.

### ISSUE THREAD

**Issue by shaileshsakaria** [basst314/ngx-webcam#29]
I am not able to open camera on "Ipad" and "Microsoft windows surface", getting following message.

{ "message" : "Could not start video source", "mediaStreamError" : {} }

Anyone have an idea?

**Comment by basst314** [comment]
Hi @shaileshsakaria,
could you provide the respective OS versions?
Also, do you get the same message on the demo page linked in the readme.md?
Thanks

**Comment by shaileshsakaria** [comment]
@basst314 

My Ipad version is 10.3.3 (14G60) - & Model - MD510HN/A - in that - the demo link also not working and yes giving below error message.

{ "message" : "enumeratedDevices() not supported." }
{ "message" : "Cannot read UserMedia from MediaDevices."}

In Windows surface - OS is Windows 10 Pro Build 10586. - Ithe demo link is working fine.  Is that issue due to below videoOptions I given?

In videoOptions, I have given this,

  public videoOptions: MediaTrackConstraints = {
    // width: {ideal: 1024},
    // height: {ideal: 576}
  };

**Comment by basst314** [comment]
Hi @shaileshsakaria,

Thanks for the quick response! Unfortunately your iPad does not support the required browser API (WebRTC/UserMedia). If you can update the OS (I believe somewhere around 11.0 they started supporting the Apis) it may work.

If the demo page works on the surface you have, then it supports the Apis (good news!).
However there seems to be an issue when requesting webcam access through the browser Api. Double check that you access your project over a secure https:// connection, otherwise many browsers deny access to the webcam.
Your video options look okay (empty), but you could try to just use the minimal demo of `<webcam></webcam>` and see what happens.

**Comment by basst314** [comment]
No reply by issue creator - closed.
