### ISSUE TITLE
Identify if webcam is allowed by user or not 

### ISSUE THREAD

**Issue by peddikishore** [basst314/ngx-webcam#32]
Hi I have an issue in identifying whether the webcam permission is allowed or blocked by the user,
I did try checking with the device list but unfortunately its always coming device available, but need to find whether the user game permission or not. 
Can anybody suggest, I did post my question on stackoverflow but unfortunately din't get any response. That's why  had to post it here.

Please help.

**Comment by basst314** [comment]
Hi @peddikishore,

sorry it took a while to get back to you.

Unfortunately there's currently no 'flag' that you could just query to get this info, but if you add the webcam-component to your page and webcam initialization was not successful (i.e. due to blocked access), then an error will be emitted through the `initError` EventEmitter of the component. 

Capture that error object and check for an error message like 'Permission denied'.
Example object: `{ "message": "Permission denied" ... }`

[The demo page](https://basst314.github.io/ngx-webcam/) will show these messages when they occur, so best try for yourself - visit the page and block webcam access.

Hope that helps.

I will still try to find out more whether checking for blocked access is possible through the browser API.

**Comment by basst314** [comment]
Hi @peddikishore,

I found a better way to check for blocked camera access:

When the camera was blocked, the webcam component publishes a `WebcamInitError` through the `initError` EventEmitter. While checking for the message is probably not a good practice (message might change), according to [Mozilla Docs](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia), the `name` attribute of the wrapped `MediaStreamError` has the value `NotAllowedError` in case webcam access was blocked / not allowed by the user.

I verified this with some example code like this:

```
  <webcam (initError)="handleInitError($event)"></webcam>

---

  public handleInitError(error: WebcamInitError): void {
    if (error.mediaStreamError && error.mediaStreamError.name === "NotAllowedError") {
      console.warn("Camera access was not allowed by user!");
    }
  }
```

Hope this is helpful!

Cheers!
