### ISSUE TITLE
Does this work in PWAs

### ISSUE THREAD

**Issue by OrangeDrangon** [basst314/ngx-webcam#37]

**Comment by basst314** [comment]
Hi @OrangeDrangon,

Please be more specific what you mean.

Did you encounter any issues? 
If so, please provide more information and/or a minimal code sample that reproduces the issue.

Thanks

**Comment by OrangeDrangon** [comment]
Upon testing in IOS. Havent tried in Android. It does not request permission to use the camera in pwa form. I do not know if this is on your end or something with my manifest.json as I am new to PWAs. It works if I am using it in Safari

**Comment by OrangeDrangon** [comment]
That wasn't coherent English let me explain. Your outstanding plugin works every where I have tested it except for on IOS after I add it to the home screen.  I was wondering if this was on your end or mine. Or just the platform in general. My guess is that it is IOS but I was just curious. I will get my code on GitHub in the upcoming hours

**Comment by basst314** [comment]
The ngx-webcam plugin works on iOS, as long as the OS is up-to-date enough. I believe Apple added the required APIs in iOS >=11.

Please verify that your iOS device is running the latest OS version.

Thanks

**Comment by OrangeDrangon** [comment]
I am running Ios 12 it only does not work when I add the app to the home screen if that makes sense. And in the main browser it works

**Comment by basst314** [comment]
I tried it with the demo page that is linked in the readme. I did the following:
* opened the demo link on the iPhone in safari
* added the web page to the home screen
* closed safari
* opened the home-screen bookmark
* safari opened and asked for webcam permissions
* after clicking „allow“ the webcam was shown successfully

Please verify the steps yourself. Launching the same url in the same browser from within the browser or homescreen should not make any difference.

**Comment by OrangeDrangon** [comment]
This problems occurs when I have an app `manifest.json`  and a `service-worker.js` making it a PWA. After further research I believe this is a limitation of PWAs on Apple's end. Here is an example so you can mess around with it.

[Repo](https://github.com/OrangeDrangon/PWA-Snapchat)
[Website](https://orangedrangon.github.io/PWA-Snapchat/)

This PWA was not working when added to home screen on IOS not tested on Android as of now.

**Comment by basst314** [comment]
I noticed that when adding your website to the home screen, iOS doesn‘t save the whole URL but just the base url.

This
https://orangedrangon.github.io/PWA-Snapchat/

Becomes this link on the homescreen:
https://orangedrangon.github.io/

When opening from the home screen it says that there‘s no webpage under this address, because the path information is not preserved.
That may be the issue.

You could try to work around it by having it hosted on a provate domain that i.e. forwards to the right path, or just run your app under the domain without additional path i formation in the url. This might work.

Thanks
