### ISSUE TITLE
ngx-camera is not working on IPad/IOS (Chrome and Safari browsers) in angular 9

### ISSUE THREAD

**Issue by vanlot** [basst314/ngx-webcam#70]
Hi Team,

Are there any ways to make ngx-camera to work in Chrome and Sarafi browsers of IOS (Ipad) when upgrading to angular 9?. After I upgraded angular 7 to angular 9, then it does not work on those browsers of IOS (IPad), although it works well on Chrome of Android.

Thank you

**Comment by basst314** [comment]
Hi @vanlot,

I've released a new version of this library (0.3.0) that bumps Angular to 9 and Typescript to >= 3.7.

Please try with this version and let me know if it resolves your issue.
Generally speaking, the library should work fine on iOS. I've tested the Live Demo page on my iPhone and it works fine.
Does the demo page run for you on your iPad?

Please also check that you're serving your App from a secure location using https://.

Thanks

**Comment by vanlot** [comment]
Hi @basst314,

Thank you for your update, it is working on Safari now, but unfortunately, it seems does not work on Chrome (IPad). Your live demo shows error message: "enumerateDevices() not supported" and "Cannot read UserMedia from MediaDevices".

Kind regards,
Van Lot

**Comment by basst314** [comment]
Hi @vanlot,

Thanks for confirming!

Unfortunately WKWebKit based browsers like Chrome on iOS can not access the necessary WebRTC/UserMedia APIs because they are currently not made accessible by Apple (yet).

See this for details:
https://bugs.webkit.org/show_bug.cgi?id=208667
and
https://bugs.chromium.org/p/chromium/issues/detail?id=752458

Hopefully Apple will fix this issue soon, until then only Safari works on iOS.

I‘m closing this issue, if you have further questions feel free to reopen or create a new one. Thanks.

**Comment by vanlot** [comment]
Hi @basst314,

Yes, thank you for your explanation!
